# config/pipeline.yaml
# para archivos sin delimitador usar null
task:
  - name: "Carga de Ventas Mensuales"
    file: "data/input/cliente.csv"
    delimiter: ";"
    encoding: "utf8"
    table_destination: "data_samples"
    schema: "dbo"
    active: true

  - name: "Carga de Oficinas Mensuales"
    file: "data/input/oficinas.csv"
    delimiter: ";"
    encoding: "utf8"
    table_destination: "oficinas"
    schema: "dbo"
    active: true

  - name: "Carga de productos Mensuales"
    file: "data/input/productos.csv"
    delimiter: ";"
    encoding: "utf8"
    table_destination: "productos"
    schema: "dbo"
    active: true
