_defaults:
  schema: public
  delimiter: ;
  crear_tabla_si_no_existe: true
  truncate_before_load: false
  active: true
task:
- name: Carga oficinas
  file: data/input/oficinas.csv
  delimiter: ;
  encoding: utf8
  table_destination: oficinas
  crear_tabla_si_no_existe: true
  truncate_before_load: false
  schema: public
  active: true
- name: Carga productos
  file: data/input/productos.csv
  delimiter: ;
  encoding: utf8
  table_destination: productos
  crear_tabla_si_no_existe: true
  truncate_before_load: false
  schema: public
  active: true
- name: Carga clientes
  file: data/input/cliente.csv
  delimiter: ;
  encoding: utf8
  table_destination: clientes
  crear_tabla_si_no_existe: true
  truncate_before_load: false
  schema: public
  active: true
- name: Carga taxi_newyork
  file: data/input/tripdata_2015-01.csv
  delimiter: ","
  encoding: utf8
  table_destination: taxi_newyork
  crear_tabla_si_no_existe: true
  truncate_before_load: false
  schema: public
  active: true